### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by louisdb03** [BoostingMy/vsts-heroku-tasks#3]
Hi I'm trying to do a push to Heroku from VSTS. I have a Rails repository that should be pushed, I've skippped the building part and trying to directly push from the master branch (normaly heroku takes care of the rest). However I'm keeping to get this error, I'm geussing I have some authentication issues, but no clue how to resolve this. Can anybody help?

```
2017-10-22T10:20:25.6280560Z ##[error]System.Management.Automation.RuntimeException: git push origin master
2017-10-22T10:20:25.6280560Z [git] /usr/bin/bash: /dev/tty: No such device or address
2017-10-22T10:20:25.6280560Z [git] error: failed to execute prompt script (exit code 1)
2017-10-22T10:20:25.6280560Z fatal: could not read Username for 'https://ghenterprise.visualstudio.com': No error
2017-10-22T10:20:25.6280560Z  ---> System.Management.Automation.RuntimeException: git push origin master
2017-10-22T10:20:25.6280560Z [git] /usr/bin/bash: /dev/tty: No such device or address
2017-10-22T10:20:25.6280560Z [git] error: failed to execute prompt script (exit code 1)
2017-10-22T10:20:25.6280560Z fatal: could not read Username for 'https://ghenterprise.visualstudio.com': No error
2017-10-22T10:20:25.6280560Z 
2017-10-22T10:20:25.6280560Z    --- End of inner exception stack trace ---
2017-10-22T10:20:25.6280560Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-10-22T10:20:25.6280560Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-10-22T10:20:25.6280560Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-10-22T10:20:25.6280560Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-10-22T10:20:25.6280560Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-10-22T10:20:25.6280560Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2017-10-22T10:20:25.6370594Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
```

**Comment by xakpc** [comment]
This module performs Heroku update by scripted `git push`
If you set your repository as an Artifact in Release Definition the script will try to perform push to original location (VisualStudio repo in your case)

I was forced to create Build Definition, remove `.git` folder and setup Publish Artifact task there. When I setup Release Definition with this artifact the script works normally

**Comment by froston** [comment]
@louisdb03 Could you find a solution?
